Feature/add accesiblemode
situmtech/cordova pull request #102
Opened 2018-11-29 10:07 UTC by AdrianRegueira

2018-11-30 14:09 UTC, adrinieto commented
Falta actualizar el CHANGELOG

2018-12-03 10:36 UTC, adrinieto requested changes

2018-12-03 10:36 UTC, adrinieto commented on src/android/app/src/main/java/es/situm/plugin/PluginHelper.java
> +                String realtimeUpdateInterval = request.getString(SitumMapper.REALTIME_UPDATE_INTERVAL);
Qué pasa si alguien lo está usando y mete un int en ese campo?

2018-12-03 10:36 UTC, adrinieto commented on src/android/app/src/main/java/es/situm/plugin/SitumMapper.java
> +  public static final String ACCESSIBLE_MODE = "accessibleMode";
Debería llamarse `accessibilityMode` igual que en  Android e iOS

2018-12-03 10:36 UTC, adrinieto commented on src/android/app/src/main/java/es/situm/plugin/PluginHelper.java
> -                if (options.has(SitumMapper.ACCESSIBLE)) {
Con esto rompemos la retrocompatibilidad. Si alguien mandaba el accesible a true le va a dejar de funcionar. Si existe el campo hay que mapearlo a uno de los modos nuevos.

2018-12-03 12:57 UTC, AdrianRegueira commented on src/android/app/src/main/java/es/situm/plugin/PluginHelper.java
> -                if (options.has(SitumMapper.ACCESSIBLE)) {
Se comprueba si ese parametro existe mas tarde, ahora la creación de DirectionsRequest se hace en SitumMapper

2018-12-03 12:58 UTC, AdrianRegueira commented on src/android/app/src/main/java/es/situm/plugin/PluginHelper.java
> +                String realtimeUpdateInterval = request.getString(SitumMapper.REALTIME_UPDATE_INTERVAL);
Ahora ya se comprueba

2018-12-03 15:15 UTC, adrinieto commented on src/android/app/src/main/java/es/situm/plugin/PluginHelper.java
> -                if (options.has(SitumMapper.ACCESSIBLE)) {
Cierto :+1:

2018-12-04 09:46 UTC, CrisBarreiro approved these changes

2018-12-04 09:47 UTC, merged