Feature/add route segments
situmtech/cordova pull request #154
Opened 2019-03-25 11:46 UTC by adrianRVSitum

2019-03-25 13:04 UTC, adrinieto requested changes

2019-03-25 13:04 UTC, adrinieto commented on CHANGELOG_UNRELEASED.md
> +
Falta que también se ha añadido a NavigationProgress.

2019-03-25 13:04 UTC, adrinieto commented on CHANGELOG_UNRELEASED.md
> +
Tanto points como segments

2019-03-25 13:04 UTC, adrinieto commented on src/ios/situmcordovaplugin/SitumLocationWrapper.m
> +    [jo setObject: segmentsJsonArray.copy forKey: @"segments"];
Aquí hai algo de lío cos espazos despois de `setObject: `

2019-03-25 13:16 UTC, adrianRVSitum commented on CHANGELOG_UNRELEASED.md
> +
Feito 👍

2019-03-25 13:17 UTC, adrianRVSitum commented on src/ios/situmcordovaplugin/SitumLocationWrapper.m
> +    [jo setObject: segmentsJsonArray.copy forKey: @"segments"];
Solucionado 👍

2019-03-26 17:01 UTC, adrinieto approved these changes

2019-03-26 17:18 UTC, merged